
var subtext = [
  "I want 10% of the royalties.",
  "Don't call me for bail if you get arrested.",
  "Really? You really want that?",
  "I'm not surprised.",
  "Have fun.",
  "That doesn't sound healthy.",
  "The things you do for your views.",
  "tbh, I'd click that",
  "Hahahaha",
  "That's a Devon joke.",
  "That might break the YouTube TOS.",
  "Don't forget the red arrow clickbait."
];

var prefixes = [
  "flaming",
  "insane",
  "ultimate",
  "drinking",
  "flipping",
  "epic",
  "going inside",
  "world's",
  "most insane",
  "escape",
  "hilarious",
  "cheesiest",
  "craziest",
  "egg",
  "huge",
  "water balloon",
  "my girlfriend",
  "my mom's",
  "my dad's",
  "my brother's",
  "my sister's",
  "gross",
  "bf vs gf",
  "funny",
  "fake"
];

var nouns = [
  "sword",
  "katana",
  "jp",
  "kyle",
  "mitch",
  "coke",
  "mentos",
  "slime",
  "goo",
  "coke and mentos",
  "10,000 calorie brownie",
  "10,000 calorie pizza",
  "10,000 calorie milkshake",
  "nerf war",
  "nerf",
  "rocket",
  "giant cup",
  "waxes my legs",
  "waxes my arms",
  "french fry",
  "golf",
  "indoor golf",
  "fidget spinner",
  "mold",
  "soccer",
  "ping pong",
  "basketball",
  "hot pepper",
  "cookie",
  "cake"
];

var suffixes = [
  "GONE WRONG",
  "(WORLD'S LARGEST)",
  "IN MY BACKYARD",
  "IN MY KITCHEN",
  "IN MY CAR",
  "IN MY OFFICE",
  "IN MY BEDROOM",
  "(BLOOD WARNING)",
  "(VOMIT WARNING)",
  "EVER",
  "ON YOUTUBE",
  "IN THE WORLD",
  "ON THE INTERNET",
  "(DANGEROUS)",
  "PRANK",
  "CHALLENGE",
  "PENALTY CHALLENGE"
];
